const menu = [
  {
    id: 1,
    title: "Paratha",
    category: "breakfast",
    price: "₹30",
    img: "./images/item-1.jfif",
    desc: `Paratha comes in different varieties.People love to have this with dahi (curd) & aachar (pickle). `,
  },
  {
    id: 2,
    title: "Chicken Biryani",
    category: "lunch",
    price: "₹45",
    img: "./images/item-2.jfif",
    desc: ` It is very wholesome and delicious. The flavours are enriched by adding a lot of spices. You can best enjoy this lunch special dish with raita.  `,
  },
  {
    id: 3,
    title: "Papri Chaat",
    category: "snacks",
    price: "₹15",
    img: "./images/item-3.jfif",
    desc: `Nothing like the crunch of freshly made papdis topped with yogurt, coriander and tamarind chutney. An authentic recipe straight from the streets of Old Delhi.`,
  },
  {
    id: 4,
    title: "Poori Sabzi",
    category: "breakfast",
    price: "₹20",
    img: "./images/item-4.jfif",
    desc: `Aloo (potato) sabzi is generally preferred in sabzi with pooris. Poori is made of wheat atta `,
  },
  {
    id: 5,
    title: "Matar Paneer",
    category: "lunch",
    price: "₹80",
    img: "./images/item-5.jfif",
    desc: ` Paneer is a rich source of proteins, combination of paneer and peas makes the dish too delicious. `,
  },
  {
    id: 6,
    title: "Samosa",
    category: "snacks",
    price: "₹10",
    img: "./images/item-6.jfif",
    desc: `These deep-fried, triangular pastries are filled with a variety of ingredients ranging from vegetables to meat, such as onions, lentils, spiced potatoes, peas, or ground meat.`,
  },
  {
    id: 7,
    title: "Idli",
    category: "breakfast",
    price: "₹10",
    img: "./images/item-7.jfif",
    desc: `It’s a famous South Indian dish for breakfast and very popular across the country. Lovely to have this with sambar and coconut chutney. `,
  },
  {
    id: 8,
    title: "Dal Makhani",
    category: "lunch",
    price: "₹50",
    img: "./images/item-8.jfif",
    desc: ` Dal makhani is also a lunch special dish which is a famous dish in Punjab. You can make dal makhani for lunch using urad dal and rajma.  `,
  },
  {
    id: 9,
    title: "Petha",
    category: "snacks",
    price: "₹7",
    img: "./images/item-9.jfif",
    desc: ` It is a translucent, soft candy made from ash gourd or the white pumpkin, usually rectangular or cylindrical in shape and comes in flavoured varieties including the Grape Petha, Chocolate Petha, Orange Petha and more.`,
  },
];
export default menu;
